import 'package:flutter/material.dart';

class AppUrls {
  static var baseUrlReputation = "https://stagingrep.mindplex.ai";
  static var baseUrl = "https://staging.mindplex.ai/wp-json";
  static var loginUrl = '$baseUrl/auth/v1/token';
  static var refreshTokenUrl = '$baseUrl/auth/v1/token/refresh';
  static var profileUrl = '$baseUrl/wp/v2/users/profile';
  static var editProfileUrl = '$baseUrl/wp/v2/users/profile';
  static var changePasswordUrl = '$baseUrl/wp/v2/users/change-password';
  static var changeProfilePictureUrl = '$baseUrl/wp/v2/users/profile-picture';
  static var registerationUrl = '$baseUrl/wp/v2/users/register';
  static var blogUrl = '$baseUrl/mp_gl/v1/posts';
  static var commentsFetch = '$baseUrl/wp/v2/comments';
  static var commentCreate = '$baseUrl/wp/v2/comment';
  static var commentDelete = '$baseUrl/wp/v2/comment/delete';
  static var commentUpdate = '$baseUrl/wp/v2/comment/update';
  static var commentLikeDislike = '$baseUrl/wp/v2/comment/like_dislike';
  static var likeDislike = '$baseUrl/wp/v2/post/like_dislike/';
  static var reactWithEmoji = '$baseUrl/wp/v2/post/react/';
  static var searchLandingUrl = '$baseUrl/mp_rp/v1/search';
  static var bookmark = '$baseUrl/mp_gl/v1/posts/bookmark/';
  static var followUrl = '$baseUrl/mp_rp/v1/user/follow';
  static var unfollowUrl = '$baseUrl/mp_rp/v1/user/unfollow';
  static var followers = '$baseUrl/mp_rp/v1/user/followers/';
  static var followings = '$baseUrl/mp_rp/v1/user/followings/';
  static var blogAddViewUrl = "$baseUrl/mp_rp/post/view_count/";
  static var draftBaseUrl = "${AppUrls.baseUrl}/mp_up/v1/post/draft/";
  static var postUrl = "${AppUrls.baseUrl}/mp_up/v1/post/";
}

var com_id = "e98776e8-32f6-4325-971c-ffc8d1188901";
var api_key = "HiF2J9gC.U7MOTTOfXdtfRsh9x0wcCM6p3kJWvg9C";
final List<String> emojiCodes = [
  "128175",
  "128152",
  "128525",
  "10024",
  "127881",
  "128079",
  "129000",
  "128564",
  "128545",
  "10060",
  "129326",
  "128169"
];
final List<String> emojis = [
  "💯",
  "💘",
  "😍",
  "✨",
  "🎉",
  "👏",
  "🟨",
  "😴",
  "😡",
  "❌",
  "🤮",
  "💩"
];

Map<String, String> codeToEmojiMap = {
  "128175": "💯",
  "128152": "💘",
  "128525": "😍",
  "10024": "✨",
  "127881": "🎉",
  "128079": "👏",
  "129000": "🟨",
  "128564": "😴",
  "128545": "😡",
  "10060": "❌",
  "129326": "🤮",
  "128169": "💩"
};
// List<String> bookmarkValue = ['added', 'removed'];

class Keys {
  static final globalkey = GlobalKey<ScaffoldState>();
}

List<String> countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (Democratic Republic of the)",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Macedonia",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Türkiye",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom(UK)",
  "United States of America(USA)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  'Virgin Islands',
  "Wallis and Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
