import 'package:get/get.dart';
import 'package:mindplex/features/blogs/models/blog_model.dart';

class PrivacyController extends GetxController {
  List<Content> contents = [
    Content(type: "h1", content: "Mindplex Privacy"),
    Content(type: "p", content: "Last Updated Nov 08, 2022"),
    Content(
        type: "p",
        content:
            "Welcome to Mindplex! This policy sets out the different areas where user privacy is concerned and outlines the obligations & requirements of the users, the website and website owners. Furthermore, the way this website processes, stores and protects user data and information will also be detailed within this policy."),
    Content(type: "h2", content: "The Website"),
    Content(
        type: "p",
        content:
            "This website and its owners take a proactive approach to user privacy and ensure the necessary steps are taken to protect the privacy of its users throughout their visiting experience. This website complies with all European Union General Data Protection Regulation (GDPR) and requirements for user privacy."),
    Content(type: "h2", content: "Data Processing"),
    Content(type: "h3", content: "Data Controller"),
    Content(
        type: "li",
        content:
            "The data controller is the natural or legal person, public authority, service or other body that, individually or together with others, determines the purposes and means of processing personal data. This position also deals with safety profiles."),
    Content(
        type: "li",
        content:
            "With regards to this website, the data controller is: Mindplex, and for any clarification or exercise of the rights of the user he can be contacted at the following email address: email@mindplex.ai or legal@mindplex.ai"),
    Content(type: "h3", content: "Data Processing Location"),
    Content(
        type: "li",
        content:
            "The processing of data, generated by the use of the services provided by Mindplex through the web portal, takes place at AWS N. Virginia, United States."),
    Content(
        type: "li",
        content:
            "In case of need, the data related to the newsletter service can be processed by individuals appointed for this purpose by the Owner, at their respective locations."),
    Content(type: "h2", content: "Use of cookies"),
    Content(type: "h3", content: "What are cookies?"),
    Content(
        type: "p",
        content:
            "Cookies are small files saved to the user’s computer’s hard drive that track, save and store information about the user’s interactions and usage of the website. This allows the website, through its server to provide the users with a tailored experience within this website."),
    Content(type: "h3", content: "What do we use cookies for?"),
    Content(
        type: "p",
        content:
            "We may use cookies to remember personal settings you have chosen at our website. In no other context do we use cookies to collect information that identifies you personally. Most of the cookies we set are automatically deleted from your computer when you leave our website or shortly afterwards."),
    Content(
        type: "p",
        content:
            "We use anonymous session cookies (short-term cookies that disappear when you close your browser) to help you navigate the website and make the most of the features. If you log into the website, application or a course as a registered user, your session cookie will also contain your user ID so that we can check which services you are allowed to access."),
    Content(
        type: "p",
        content:
            "This website uses tracking software to monitor its visitors to better understand how they use it. This software is provided by Google Analytics which uses cookies to track visitor usage. The software will save a cookie to your computer’s hard drive in order to track and monitor your engagement and usage of the website, but will not store, save or collect personal information."),
    Content(
        type: "p",
        content:
            "Should users wish to deny the use and saving of cookies from this website onto their computer’s hard drive, they should take necessary steps within their web browser’s security settings to block all cookies from this website and its external serving vendors."),
    Content(type: "h3", content: "Types of Cookies"),
    Content(
        type: "li",
        content:
            "The Mindplex website uses cookies to make the user's browsing experience easier and more intuitive: cookies are small strings of text used to store some information that may concern the user, his preferences or the device used to access the Internet (computer, tablet or mobile) and these cookies are mainly used to adapt the operation of the website to the user's expectations, offering a more personalised browsing experience and memorising the choices made previously."),
    Content(
        type: "li",
        content:
            "A cookie consists of a reduced set of data transferred from a web server to the user's browser and it can only be read by the server that made the transfer. This is not executable code and does not transmit viruses."),
    Content(
        type: "li",
        content:
            "Cookies do not record any personal information and any identifiable information will not be stored. If you want, you can prevent the saving of some or all cookies. However, in this case, the use of the website and the offered services could be compromised. To proceed without changing the options related to cookies, simply continue browsing."),
    Content(type: "h2", content: "Technical Cookies"),
    Content(
        type: "li",
        content:
            "1. There are many technologies used to store information on the user's computer, which are then collected by the websites. Among these, the best known and used one is based on HTML cookies. They are used for navigation and to facilitate the access and use of the website to the user. They are necessary for the transmission of communications on the electronic network and for the supplier, to provide the service requested by the customer."),
    Content(
        type: "li",
        content:
            "2. The settings to manage or deactivate cookies may vary depending on the used internet browser. In any case, the user can manage or request the general deactivation or cancellation of cookies, modifying the settings of his internet browser. This deactivation can slow down or prevent access to some parts of the website."),
    Content(
        type: "li",
        content:
            "3. The use of technical cookies allows the safe and efficient use of the website."),
    Content(
        type: "li",
        content:
            "4. Cookies that are inserted in the browser and retransmitted by Google Analytics or by the statistics service of blogger providers or similar services are considered as technical only if they are used for the purpose of optimising the website directly from the owner of the website, which can collect information in aggregate form about the number of users and how they visit the website. Under these conditions, the same rules provided for technical cookies, in terms of privacy policy and approval, are applied to analytics cookies."),
    Content(
        type: "li",
        content:
            "5. From the duration point of view, it is possible to identify the temporary session cookies, which are deleted automatically at the end of the browsing session and are used to identify the user and thus avoid logging into each visited page, and permanent ones, which remain active in the PC until expiry or cancellation by the user."),
    Content(
        type: "li",
        content:
            "6. Session cookies may be installed in order to allow the access and the continuity of operations in the reserved area of the platform as an authenticated user."),
    Content(
        type: "li",
        content:
            "7. They are not permanently stored, but only for the duration of the navigation, until the browser is closed, and disappear when the browser is closed. Their use is strictly limited to the transmission of session identifiers, consisting of random numbers generated by the server and needed to allow the safe and efficient browsing of the website."),
    Content(type: "h2", content: "Third-Party Cookies"),
    Content(
        type: "li",
        content:
            "1. Depending on the provenance, it’s possible to identify the cookies that are sent to the browser directly from the website that the user is browsing and those owned by third parties, sent to the computer from other websites and not from the one that the user is browsing."),
    Content(
        type: "li",
        content: "2. Permanent cookies are often third-party cookies."),
    Content(
        type: "li",
        content:
            "3. The majority of third-party cookies consists of tracking cookies, used to identify online behaviour, understand the interests and then customise the advertising proposals for users."),
    Content(
        type: "li",
        content:
            "4. Third-party analytical cookies may be installed. They are sent from the domains of the aforementioned third parties that are external to the website."),
    Content(
        type: "li",
        content:
            "5. The third-party analytical cookies are used to provide information about the behaviour of users on Mindplex’s platform. The detection is anonymous, in order to monitor the performance and improve the usability of the website. The third-party profiling cookies are used to create users’ profiles, in order to propose advertising messages that follow the choices expressed by the users."),
    Content(
        type: "li",
        content:
            "6. The use of these cookies is governed by the rules set by the third parties themselves, therefore, users are invited to read the privacy policies and the indications to manage or disable the cookies, that are published on the related web pages."),
    Content(type: "h2", content: "Profiling Cookies"),
    Content(
        type: "li",
        content:
            "1. Profiling cookies are used to create profiles related to the user and they are used in order to send advertising messages that follow the preferences expressed by the user when surfing the net."),
    Content(
        type: "li",
        content:
            "2. When these types of cookies are used, the user must give explicit consent."),
    Content(type: "h2", content: "Processed Data"),
    Content(type: "h3", content: "Data Processing Mode"),
    Content(
        type: "p",
        content:
            "The processing of personal data is fulfilled mainly using electronic procedures and supports (database, backend application, etc.) for the time strictly necessary to achieve the purposes for which the data are collected and, in any case, in accordance with the principles of lawfulness, correctness, non-excess and relevance considered by the current privacy legislation."),
    Content(
        type: "li",
        content:
            "1. This website uses log files where it keeps information collected in an automated manner during users’ browses. The information collected could be the following ones:"),
    Content(type: "li", content: "internet protocol (IP) address;"),
    Content(
        type: "li",
        content:
            "type of browser and device parameters used to connect to the website;"),
    Content(
        type: "li", content: "name of the Internet service provider (ISP);"),
    Content(type: "li", content: "date and time of visit;"),
    Content(
        type: "li",
        content:
            "web page that brings visitors to Mindplex (referral) and exit pages;"),
    Content(type: "li", content: "possibly the number of clicks."),
    Content(
        type: "li",
        content:
            "2. The aforementioned information is processed in an automated way and collected in an exclusively aggregated way, in order to verify the correct operation of the website, and for security reasons. This information will be processed according to the legitimate interests of the data controller."),
    Content(
        type: "li",
        content:
            "3. For security purposes (email spam filters, firewalls, virus and malware detection), the automatically recorded data may possibly also include personal data such as the IP address, which could be used, in accordance with applicable laws, in order to block attempts to damage the website itself or to damage other users, or in any case of harmful or criminal activities. Such data is never used for the identification or profiling of the user, but only for the protection of the website and its users. This information will be processed according to the legitimate interests of the data controller."),
    Content(
        type: "li",
        content:
            "4. The data received by Mindplex will be used exclusively for the provision of the service and only for the time needed to provide the service."),
    Content(
        type: "li",
        content:
            "5. By registering on the Mindplex platform, users can create their own personal profile through the control panel."),
    Content(type: "h3", content: "Purposes of Data Processing"),
    Content(
        type: "li",
        content:
            "1. The personal data of the users, collected through the registration to the platform, are used to guarantee a correct association between the controller and the user, and to offer trust and transparency to the users of the platform."),
    Content(
        type: "li",
        content:
            "2. Data collected by the website during its operation are used for the purposes indicated in this document and kept for the time strictly necessary to carry out the specified activities, and in any case not later than 5 years."),
    Content(
        type: "li",
        content:
            "3. Data used for security purposes (block the attempts to damage the website, etc.) are kept for the time strictly necessary to achieve the previously indicated purpose."),
    Content(type: "h3", content: "Data Provided by the User"),
    Content(
        type: "li",
        content:
            "1. Users, individual or corporate may voluntarily or be required to provide some personal and sensitive data, name, street address, telephone number, e-mail address, wireless e-mail address, demographic information and other information that may identify you sending identity documents and proof of residence, commercial and trade licences, establishment records needed for the identification, verification and geolocation procedures. Individuals and corporations can decide which data they want to send to the platform to be correctly identified and geolocated, in order to increase their trust level and be approved as a valid client."),
    Content(
        type: "li",
        content:
            "2. The identified and geolocated users, individual and corporate, will be able to enjoy more services and benefit from a greater level of trust in the platform and by its users."),
    Content(
        type: "li",
        content:
            "3. The verification of the information provided by the user may be transferred to an appointed external company or third party such as a KYC provider; the verification operations are performed by appointed, specialised personnel internal to Mindplex or to an appointed third-party, which shall follow rigorous verification procedures."),
    Content(
        type: "li",
        content:
            "4. All data is used only and exclusively in case that the users, individual or corporate, are required to be identified, verified and geolocated, so as to verify the correctness of the provided information to perform related services and activities provided by the platform."),
    Content(
        type: "li",
        content:
            "5. As indicated above, the optional, explicit and voluntary sending of emails to the Mindplex’s email addresses entails the subsequent acquisition of the sender's address, necessary to respond to the requests, as well as any other personal data included in the message."),
    Content(
        type: "li",
        content:
            "6. As indicated above, Mindplex may send newsletter and marketing emails to the subscribed users of the platform, this is an option that users can OPT-IN."),
    Content(
        type: "li",
        content:
            "7. If necessary, to increase the level of transparency and information regarding specific requests for personal and / or sensitive data and the related processing, specific policy summaries will be shown to the user and they will be progressively reported or displayed on the website pages, predisposed for specific on demand services."),
    Content(type: "h2", content: "Support in Configuring Your Browser"),
    Content(
        type: "li",
        content:
            "1. Users can manage cookies also through the setting options of their browser. However, deleting cookies from their browser, they may remove the preferences they have set for the website."),
    Content(
        type: "li",
        content:
            "2. For further information and support, it is possible to also visit the specific help page of the web browser:"),
    Content(
        type: "li",
        content:
            "Internet Explorer: http://windows.microsoft.com/en-us/windows-vista/block-or-allow-cookies"),
    Content(
        type: "li",
        content:
            "Firefox: https://support.mozilla.org/en-us/kb/enable-and-disable-cookies-website-preferences"),
    Content(type: "li", content: "Safari: http://www.apple.com/legal/privacy"),
    Content(
        type: "li",
        content: "Chrome: https://support.google.com/accounts/answer/61416"),
    Content(
        type: "li",
        content:
            "Opera: http://www.opera.com/help/tutorials/security/cookies/"),
    Content(type: "h3", content: "Plugin Social Network"),
    Content(
        type: "li",
        content:
            "1. This website also incorporates plugins and/or buttons for social networks, in order to allow the easy sharing of content on users' favourite social networks. These plugins are programmed in order to not set any cookies when opening the web page so as to safeguard the privacy of users. It is possible that cookies are set, if planned by social networks, only when the user voluntarily uses the plugin. Please note that if the user browses the website while he/she is logged into the social network, then he/she has already agreed to use cookies conveyed through this website when signed in the social network."),
    Content(
        type: "li",
        content:
            "2. The collection and use of information obtained thanks to the plugins are governed by the respective social networks’ privacy policies, to whom it is required to refer:"),
    Content(
        type: "li", content: "Facebook: https://www.facebook.com/help/cookies"),
    Content(
        type: "li",
        content:
            "Twitter: https://help.twitter.com/en/rules-and-policies/twitter-cookies"),
    Content(
        type: "li",
        content: "Pinterest: https://policy.pinterest.com/en/privacy-policy"),
    Content(
        type: "li",
        content: "Instagram: https://help.instagram.com/402411646841720"),
    Content(
        type: "li",
        content: "Linkedin: https://www.linkedin.com/legal/cookie-policy"),
    Content(type: "h2", content: "User Rights"),
    Content(
        type: "li",
        content:
            "1. The Mindplex website therefore informs the user about the existence of:"),
    Content(
        type: "li",
        content:
            "the right of the interested party to ask the data controller for access to their personal data to update, rectify, integrate or limit processes related to them or to oppose, for legitimate reasons, to their treatment, in addition to the right to data portability;"),
    Content(
        type: "li",
        content:
            "the right to request cancellation, the transformation into anonymous form or blocking of processed data in violation of the law, including those whose retention is unnecessary for the purposes where the data have been collected or subsequently processed;"),
    Content(
        type: "li",
        content:
            "the right to obtain the attestation that the operations of updating, rectification, integration of data, cancellation, blocking of data, transformation have been brought to the attention, also in relation to their content, of those that received or managed those data, except in the case where such fulfillments are not possible to deliver or they require a manifestly disproportionate effort in comparison with the protected right."),
    Content(
        type: "li",
        content:
            "2. Requests can be made directly through the user’s personal control panel in the Mindplex website, or alternatively via email addressed to the Data Controller, without formalities or, alternatively, using the model provided by the Data Protection Supervisor, or sending an email to: email@mindplex.ai or legal@mindplex.ai"),
    Content(
        type: "li",
        content:
            "3. If the treatment is based on express consent to the use – or to express consent to the use of genetic, biometric, health-related data, data that reveal religious beliefs, philosophical or union membership, data that reveal racial or ethnic origin, political opinions - the user has the right to revoke the consent at any time without compromising the lawfulness of the treatment, based on the consent given prior to the revocation."),
    Content(
        type: "li",
        content:
            "4. Likewise, in case of violation of the law, the user has the right to complain about it to the Data Protection Supervisor, as it is the authority responsible for monitoring the data processing in the US."),
    Content(type: "h2", content: "Personal Information"),
    Content(
        type: "li",
        content:
            "Whilst using our website, software applications or services, you may be required to provide personal information (name, address, email, account details, etc.). We will use this information to administer our website, applications, client databases and marketing material. We will ensure that all personal information supplied is held securely in accordance with the General Data Protection Regulation (EU) 2016/679. Further, by providing telephone, fax and email details, you consent to Mindplex contacting you using that method. You have the right at any time to request a copy of the personal information we hold on you. Should you wish to receive a copy of this, or would like to be removed from our database, please contact us at email@mindplex.ai or legal@mindplex.ai"),
    Content(type: "h2", content: "Information Collection and Use"),
    Content(type: "h3", content: "How do we collect information?"),
    Content(
        type: "li",
        content: "Mindplex collects information in two possible ways:"),
    Content(
        type: "li",
        content:
            "1. When you directly give it to us (“Directly Provided Data”)"),
    Content(
        type: "li",
        content:
            "When you sign up for our site, interact with content/other users, purchase our products or communicate with us, you may choose to voluntarily give us certain information – for example, by filling in text boxes or completing registration forms. All this information requires a direct action by you at that time in order for us to receive it."),
    Content(
        type: "li",
        content:
            "2. When you give us permission to obtain from other accounts (“User Authorised Data”)"),
    Content(
        type: "li",
        content:
            "Depending on your settings or the privacy policies for other online services, you may give us permission to obtain information from your account with those other services. For example, this can be via social media or by choosing to send us your location data when accessing our website from your smartphone."),
    Content(type: "h3", content: "How Long Do We Keep Your Data For?"),
    Content(
        type: "li",
        content:
            "Mindplex will not retain your personal information longer than necessary. We will hold onto the information you provide either while your account is in existence, or as needed to be able to provide the Services to you, or (in the case of any contact you may have with our Customer Care team) for as long as is necessary to provide support-related reporting and trend analysis only."),
    Content(
        type: "li",
        content:
            "If legally required or if it is reasonably necessary to meet regulatory requirements, resolve disputes, prevent fraud and abuse, or enforce our Terms and Conditions, we may also retain some of your information for a limited period of time as required, even after you have closed your account or it is no longer needed to provide the Services to you."),
    Content(type: "h3", content: "Registration Forms"),
    Content(
        type: "li",
        content:
            "Mindplex will not sell or rent your personally identifiable information, gathered as a result of filling out the site registration form, to anyone."),
    Content(type: "h3", content: "Choosing How We Use Your Data"),
    Content(
        type: "li",
        content:
            "We understand that you trust us with your personal information and we are committed to ensuring you can manage the privacy and security of your personal information yourself."),
    Content(
        type: "li",
        content:
            "With respect to the information relating to you that ends up in our possession, and recognizing that it is your choice to provide us with your personally identifiable information, we commit to giving you the ability to do all of the following:"),
    Content(
        type: "li",
        content:
            "You can verify the details you have submitted to Mindplex by contacting our customer services team via email@mindplex.ai or legal@mindplex.ai. Our security procedures mean that we may request proof of identity before we reveal information, including your e-mail address and possibly your address."),
    Content(
        type: "li",
        content:
            "You can also contact us by the same method to change, correct, or delete your personal information controlled by Mindplex regarding your profile at any time. Please note though that, if you have shared any information with others through social media channels, that information may remain visible, even if your account is deleted."),
    Content(
        type: "li",
        content:
            "You are also free to close your account through our account settings. If you do so, your account will be deactivated. However, we may retain archived copies of your information as required by law or for legitimate business purposes (including to help address fraud and spam)."),
    Content(
        type: "li",
        content:
            "You can unsubscribe from receiving marketing emails from us by clicking the “unsubscribe” link at the bottom of any email. Once you do this, you will no longer receive any emails from us."),
    Content(
        type: "li",
        content:
            "You can request a readable copy of the personal data we hold on you at any time. To do this, please contact us on email@mindplex.ai or legal@mindplex.ai"),
    Content(
        type: "li",
        content:
            "Please note, we are constantly reviewing how we process and protect data. Therefore, changes to our policy may occur at any time. We will endeavour to publicise any changes"),
    Content(type: "h2", content: "Data Transfer To Extra Countries"),
    Content(
        type: "li",
        content:
            "1. This website may share some of the collected data with services located outside AWS United States. In particular with Google, Facebook and Microsoft (LinkedIn) through social plugins and the Google Analytics service. The transfer is authorised and strictly regulated, so no further consent is required. The companies mentioned above guarantee their participation in the Privacy Shield."),
    Content(
        type: "li",
        content:
            "2. Data may be transferred to third countries that may not comply with the conditions set out in European Union General Data Protection Regulation (GDPR)."),
    Content(type: "h2", content: "Security About Provided Data"),
    Content(
        type: "li",
        content:
            "1. This website processes the data of users in a lawful and correct manner, adopting appropriate security measures to prevent unauthorised access, disclosure, modification or unauthorised destruction of data."),
    Content(
        type: "li",
        content:
            "2. Processing is carried out using IT and/or cloud service tools, with organisational methods and with techniques strictly related to the indicated purposes. The data provided by the users, individual and corporates, for identification, verification and geolocation are sent in encrypted form between the individual and corporates and the web platform, and through a daily procedure are transferred and stored offline in an isolated, safe and protected environment, in accordance with the current legislation."),
    Content(
        type: "li",
        content:
            "3. In addition to the Data Controller, in some cases, other employees involved in the website’s and cloud operations (administrative, commercial, marketing, legal department or system administrators) or external subjects (such as suppliers of third-party technical services, courier and postal services, hosting providers, IT companies, communication agencies) may have access to the data.")
  ];
}
